# Generated by Django 2.1.2 on 2018-11-27 16:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CentroEscolar',
            fields=[
                ('id_centro', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('id_dep', models.SmallIntegerField(blank=True, null=True)),
                ('nombre_centro', models.CharField(blank=True, max_length=255, null=True)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono_centro', models.CharField(blank=True, max_length=20, null=True)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono_direc', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'centro_escolar',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id_dep', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_dep', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'departamento',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='EstadoProyecto',
            fields=[
                ('id_estado', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'estado_proyecto',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_muni', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_muni', models.CharField(blank=True, max_length=255, null=True)),
                ('id_dep', models.ForeignKey(db_column='id_dep', on_delete=django.db.models.deletion.PROTECT, to='modelos.Departamento')),
            ],
            options={
                'db_table': 'municipio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Prioridad',
            fields=[
                ('id_priori', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_prioridad', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'prioridad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proveedores',
            fields=[
                ('id_proveedor', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_empresa', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('nit', models.CharField(blank=True, max_length=50, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'proveedores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Proyectos',
            fields=[
                ('id_proyecto', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_proyecto', models.CharField(blank=True, max_length=100, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('tiempo_estimado', models.DecimalField(blank=True, decimal_places=0, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'proyectos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id_rol', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('apellido', models.CharField(blank=True, max_length=100, null=True)),
                ('institucion', models.CharField(blank=True, max_length=255, null=True)),
                ('nickname', models.CharField(blank=True, max_length=50, null=True)),
                ('contrasenia', models.CharField(blank=True, max_length=50, null=True)),
                ('id_rol', models.ForeignKey(blank=True, db_column='id_rol', null=True, on_delete=django.db.models.deletion.PROTECT, to='modelos.Roles')),
            ],
            options={
                'db_table': 'usuario',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ProveedorProyecto',
            fields=[
                ('id_proyecto', models.OneToOneField(db_column='id_proyecto', on_delete=django.db.models.deletion.PROTECT, primary_key=True, serialize=False, to='modelos.Proyectos')),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('costo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('numero_tareas', models.IntegerField(blank=True, null=True)),
                ('tarea_actual', models.IntegerField(blank=True, null=True)),
                ('id_estado', models.ForeignKey(blank=True, db_column='id_estado', null=True, on_delete=django.db.models.deletion.PROTECT, to='modelos.EstadoProyecto')),
            ],
            options={
                'db_table': 'proveedor_proyecto',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='proyectos',
            name='id_centro',
            field=models.ForeignKey(blank=True, db_column='id_centro', null=True, on_delete=django.db.models.deletion.PROTECT, to='modelos.CentroEscolar'),
        ),
        migrations.AddField(
            model_name='proyectos',
            name='id_priori',
            field=models.ForeignKey(blank=True, db_column='id_priori', null=True, on_delete=django.db.models.deletion.PROTECT, to='modelos.Prioridad'),
        ),
        migrations.AddField(
            model_name='proveedores',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.PROTECT, to='modelos.Usuario'),
        ),
        migrations.AddField(
            model_name='centroescolar',
            name='id_muni',
            field=models.ForeignKey(blank=True, db_column='id_muni', null=True, on_delete=django.db.models.deletion.PROTECT, to='modelos.Municipio'),
        ),
        migrations.AddField(
            model_name='centroescolar',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.PROTECT, to='modelos.Usuario'),
        ),
        migrations.AddField(
            model_name='proveedorproyecto',
            name='id_proveedor',
            field=models.OneToOneField(db_column='id_proveedor', on_delete=django.db.models.deletion.PROTECT, to='modelos.Proveedores'),
        ),
        migrations.AlterUniqueTogether(
            name='municipio',
            unique_together={('id_muni', 'id_dep')},
        ),
        migrations.AlterUniqueTogether(
            name='proveedorproyecto',
            unique_together={('id_proyecto', 'id_proveedor')},
        ),
    ]
